import { Component } from '@angular/core';
import { Product } from '../types/productType';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'container',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './container.component.html',
  styleUrl: './container.component.css',
})
export class ContainerComponent {
  products: Product[] = [
    {
      id: 1,
      name: 'Laptop',
      category: 'Electronics',
      price: 1200,
      inStock: true,
      specifications: {
        weight: 2.5,
        dimensions: {
          length: 14,
          width: 10,
          height: 1,
        },
        color: 'Silver',
        material: 'Aluminum',
        additionalAttribute1: 'High Resolution Display',
        additionalAttribute2: 16,
        additionalAttribute3: true,
        additionalAttribute4: ['Touchscreen', 'Backlit Keyboard'],
        additionalAttribute5: new Date('2024-01-23'),
      },
    },
    {
      id: 2,
      name: 'Running Shoes',
      category: 'Footwear',
      price: 80,
      inStock: false,
      specifications: {
        weight: 0.8,
        dimensions: {
          length: 12,
          width: 4,
          height: 6,
        },
        color: 'Blue',
        material: 'Mesh',
        additionalAttribute1: 'Cushioned Insole',
        additionalAttribute2: 10,
        additionalAttribute3: false,
        additionalAttribute4: ['Breathable', 'Shock Absorption'],
        additionalAttribute5: new Date('2024-01-24'),
      },
    },
    {
      id: 3,
      name: 'Coffee Maker',
      category: 'Appliances',
      price: 50,
      inStock: true,
      specifications: {
        weight: 3,
        dimensions: {
          length: 8,
          width: 6,
          height: 12,
        },
        color: 'Black',
        material: 'Plastic',
        additionalAttribute1: 'Programmable Timer',
        additionalAttribute2: 8,
        additionalAttribute3: true,
        additionalAttribute4: ['Auto Shut-off', 'Easy to Clean'],
        additionalAttribute5: new Date('2024-01-25'),
      },
    },
    {
      id: 4,
      name: 'Smartphone',
      category: 'Electronics',
      price: 800,
      inStock: true,
      specifications: {
        weight: 0.5,
        dimensions: {
          length: 6,
          width: 3,
          height: 0.3,
        },
        color: 'Black',
        material: 'Glass and Metal',
        additionalAttribute1: '5G Connectivity',
        additionalAttribute2: 128,
        additionalAttribute3: true,
        additionalAttribute4: ['Triple Camera Setup', 'Face Unlock'],
        additionalAttribute5: new Date('2024-01-26'),
      },
    },
    {
      id: 5,
      name: 'Backpack',
      category: 'Fashion',
      price: 40,
      inStock: true,
      specifications: {
        weight: 0.8,
        dimensions: {
          length: 16,
          width: 8,
          height: 20,
        },
        color: 'Gray',
        material: 'Canvas',
        additionalAttribute1: 'Laptop Compartment',
        additionalAttribute2: 25,
        additionalAttribute3: false,
        additionalAttribute4: ['Adjustable Straps', 'Water-resistant'],
        additionalAttribute5: new Date('2024-01-27'),
      },
    },
    {
      id: 6,
      name: 'Gaming Console',
      category: 'Entertainment',
      price: 300,
      inStock: true,
      specifications: {
        weight: 2,
        dimensions: {
          length: 12,
          width: 8,
          height: 2,
        },
        color: 'Red',
        material: 'Plastic',
        additionalAttribute1: '4K HDR Graphics',
        additionalAttribute2: 500,
        additionalAttribute3: true,
        additionalAttribute4: ['Wireless Controller', 'Online Multiplayer'],
        additionalAttribute5: new Date('2024-01-28'),
      },
    },
    {
      id: 7,
      name: 'Desk Chair',
      category: 'Furniture',
      price: 120,
      inStock: false,
      specifications: {
        weight: 10,
        dimensions: {
          length: 24,
          width: 20,
          height: 36,
        },
        color: 'Black',
        material: 'Leather',
        additionalAttribute1: 'Adjustable Height',
        additionalAttribute2: 150,
        additionalAttribute3: true,
        additionalAttribute4: ['Ergonomic Design', 'Swivel Base'],
        additionalAttribute5: new Date('2024-01-29'),
      },
    },
    {
      id: 8,
      name: 'Digital Camera',
      category: 'Electronics',
      price: 500,
      inStock: true,
      specifications: {
        weight: 1,
        dimensions: {
          length: 5,
          width: 3,
          height: 2,
        },
        color: 'Silver',
        material: 'Metal',
        additionalAttribute1: '20 Megapixel Sensor',
        additionalAttribute2: 64,
        additionalAttribute3: false,
        additionalAttribute4: ['4K Video Recording', 'Image Stabilization'],
        additionalAttribute5: new Date('2024-01-30'),
      },
    },
    {
      id: 9,
      name: 'Smart Thermostat',
      category: 'Home Automation',
      price: 80,
      inStock: true,
      specifications: {
        weight: 0.3,
        dimensions: {
          length: 3,
          width: 3,
          height: 1,
        },
        color: 'White',
        material: 'Plastic',
        additionalAttribute1: 'Wi-Fi Connectivity',
        additionalAttribute2: 1,
        additionalAttribute3: true,
        additionalAttribute4: ['Programmable', 'Energy Efficient'],
        additionalAttribute5: new Date('2024-01-31'),
      },
    },
    {
      id: 10,
      name: 'Blender',
      category: 'Kitchen Appliances',
      price: 60,
      inStock: true,
      specifications: {
        weight: 1.5,
        dimensions: {
          length: 8,
          width: 6,
          height: 10,
        },
        color: 'Green',
        material: 'Plastic',
        additionalAttribute1: 'Multiple Speeds',
        additionalAttribute2: 12,
        additionalAttribute3: false,
        additionalAttribute4: ['Dishwasher Safe', 'Smoothie Mode'],
        additionalAttribute5: new Date('2024-02-01'),
      },
    },
  ];
}
